#!/usr/bin/env python3
"""Property 8: every root module has a committed lock file covering every provider and platform.

Three separate failures, and only the first is obvious.

MISSING LOCK. `accounts/dev` and `accounts/prod` had no committed `.terraform.lock.hcl` at all,
so CI and a laptop were free to resolve different provider versions for the layer that owns the
permissions boundary. Found by noticing `make validate` generating them as untracked files.

PROVIDER DECLARED BUT ABSENT FROM THE LOCK. Adding a provider to `required_providers` without
re-locking leaves the version unconstrained for that one provider, which is the same defect as
having no lock, scoped to whatever was added most recently.

TOO FEW PLATFORMS LOCKED. This is the one that actually bit this repository. `terraform
providers lock` records one `h1:` hash per platform, and a lock generated by a plain
`terraform init` on a laptop contains ONE — darwin only. CI on linux then fails with "provider
does not have a package available for your current platform", an error that names the platform
but not the cause, and that appears on a PR which changed nothing about providers.

WHAT THIS CAN AND CANNOT CHECK, because the first version of this script got it wrong. A lock
file does NOT record platform names anywhere — platform identity lives inside the hashes, which
are opaque. So grepping for "linux_amd64" matches nothing, in every lock file, including
correct ones. The first version did exactly that and reported all eight root modules as broken.

What is checkable is the COUNT: one `h1:` per platform per provider. So a provider with four
h1 hashes was locked for four platforms, and a provider with one was locked on somebody's
laptop. This script asserts the count, and does not claim to know which platforms they are.

No credentials and no network: this reads files.
"""

from __future__ import annotations

import pathlib
import re
import sys

# The platforms this repository locks for: two developer architectures and two CI ones.
EXPECTED_PLATFORMS = ["darwin_arm64", "darwin_amd64", "linux_amd64", "linux_arm64"]

# One h1 hash per platform per provider. Fewer than this many means the lock was generated
# without the -platform flags, which is the laptop-only trap.
MIN_H1_PER_PROVIDER = len(EXPECTED_PLATFORMS)

# WARNED ABOUT, NOT ENFORCED, and the reason is a constraint rather than an opinion.
#
# `bootstrap/seed` and `bootstrap/org-structure` both carry single-platform locks, which is a
# genuine instance of the defect this script exists to catch. The design states bootstrap is
# "the layer this effort is not permitted to touch", so they are reported and do not fail the
# check.
#
# An exception that silently passed would hide the finding, which is the opposite of the point.
# It prints as WARN with the reason attached, so the next person to own bootstrap sees it.
WARN_ONLY = ("bootstrap/seed", "bootstrap/org-structure")

REQUIRED_PROVIDERS_RE = re.compile(r"required_providers\s*\{(.*?)\n  \}", re.S)
SOURCE_RE = re.compile(r'source\s*=\s*"([^"]+)"')
LOCK_PROVIDER_RE = re.compile(r'^provider\s+"([^"]+)"', re.M)
# Each provider block, so h1 hashes can be counted per provider rather than per file — a file
# total would let one well-locked provider mask another that is laptop-only.
LOCK_BLOCK_RE = re.compile(r'^provider\s+"([^"]+)"\s*\{(.*?)^\}', re.M | re.S)


def root_modules(repo: pathlib.Path) -> list[pathlib.Path]:
    """Directories that are run in, not called from.

    A root module is identified by declaring a backend. That is what distinguishes it from a
    reusable module, which must not declare one — module convention 1.
    """
    found: set[pathlib.Path] = set()
    for tf in repo.rglob("*.tf"):
        parts = tf.parts
        if ".terraform" in parts or "modules" in parts or ".claude" in parts:
            continue
        if re.search(r'^\s*backend\s+"', tf.read_text(), re.M):
            found.add(tf.parent)
    return sorted(found)


def declared_providers(d: pathlib.Path) -> set[str]:
    """Provider source addresses named in required_providers across the directory's .tf files."""
    out: set[str] = set()
    for tf in d.glob("*.tf"):
        for block in REQUIRED_PROVIDERS_RE.findall(tf.read_text()):
            for src in SOURCE_RE.findall(block):
                out.add(src if "/" in src and src.count("/") == 2 else f"registry.terraform.io/{src}")
    return out


def main() -> int:
    repo = pathlib.Path(__file__).resolve().parents[1]
    roots = root_modules(repo)
    if not roots:
        print("  no root modules found — the detection is wrong, which is worse than a failure")
        return 2

    print(f"\n  Property 8 — lock files across {len(roots)} root module(s)")
    print("  " + "─" * 72)

    problems: list[str] = []
    warnings: list[str] = []

    for d in roots:
        rel = d.relative_to(repo)
        lock = d / ".terraform.lock.hcl"

        if not lock.exists():
            print(f"  {str(rel):<32} NO LOCK FILE")
            problems.append(f"{rel} has no .terraform.lock.hcl, so nothing pins its provider versions")
            continue

        text = lock.read_text()
        locked = set(LOCK_PROVIDER_RE.findall(text))
        declared = declared_providers(d)

        # Per provider, not per file: a file total lets one well-locked provider hide another
        # that was locked on a laptop.
        h1_counts = {
            name: len(re.findall(r'"h1:', body))
            for name, body in LOCK_BLOCK_RE.findall(text)
        }
        thin = {n: c for n, c in h1_counts.items() if c < MIN_H1_PER_PROVIDER}

        warn_only = str(rel) in WARN_ONLY
        notes = []
        missing = declared - locked
        if missing:
            notes.append(f"declared but not locked: {', '.join(sorted(missing))}")
            (warnings if warn_only else problems).append(
                f"{rel}: declared but not locked — {', '.join(sorted(missing))}")
        if thin:
            detail = ", ".join(f"{n.split('/')[-1]}={c}" for n, c in sorted(thin.items()))
            notes.append(f"{'WARN' if warn_only else 'TOO FEW PLATFORMS'} ({detail})")
            (warnings if warn_only else problems).append(
                f"{rel}: {detail} — fewer than {MIN_H1_PER_PROVIDER} h1 hashes means the lock was "
                f"generated without -platform flags, so CI on a different architecture fails with "
                f"'provider does not have a package available for your current platform'"
            )

        platforms = min(h1_counts.values()) if h1_counts else 0
        status = "OK" if not notes else "; ".join(notes)
        print(f"  {str(rel):<32} {len(locked)} provider(s), {platforms} platform(s)   {status}")

    if warnings:
        print("\n  WARNINGS — real instances of this defect, in a layer this effort may not change")
        print("  " + "─" * 72)
        for w in warnings:
            print(f"  ! {w}")
        print("  The design records bootstrap as off limits, so these are reported rather than")
        print("  fixed. Whoever owns bootstrap should re-lock with the -platform flags below.")

    if problems:
        print("\n  FAILED")
        print("  " + "─" * 72)
        for p in problems:
            print(f"  * {p}")
        print("\n  Fix with, in the offending directory:")
        print("    terraform init -backend=false")
        print("    terraform providers lock \\")
        print("      " + " \\\n      ".join(f"-platform={p}" for p in EXPECTED_PLATFORMS))
        return 1

    print(f"\n  every enforced root module is locked for {MIN_H1_PER_PROVIDER} platforms"
          + (f", with {len(warnings)} warning(s) above" if warnings else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
